### ISSUE TITLE
Config.json or .env

### ISSUE THREAD

**Issue by j-dogcoder** [discord-community/bot#2]
It would be useful if an example-config.json or .env was provided so we could see what variables we need to fill.

**Comment by Quatrecentquatre-404** [comment]
According to the code, there is my config.json :
```json
{
    "prefix": "PREFIX",
    "token": "TOKEN",
    "DEFAULT": "EMBED_COLOR"
}
``` 
And for the .env file, the only visible thing is :
```.env
TOKEN="TOKEN"
```

**Comment by j-dogcoder** [comment]
Thanks for the response @Quatrecentquatre-404. Is there no need for a github api key?

**Comment by Quatrecentquatre-404** [comment]
> Thanks for the response @Quatrecentquatre-404. Is there no need for a github api key?

If yes, it's not mentionned on the code. 🤷‍♂️

**Comment by j-dogcoder** [comment]
> > Thanks for the response @Quatrecentquatre-404. Is there no need for a github api key?
> 
> If yes, it's not mentionned on the code. 🤷‍♂️

Ok!
